//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Resources;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyDescription("github.com.trondr Op Tools")]
[assembly: AssemblyCompany("github.com.trondr")]
[assembly: AssemblyProduct("trondr.OpTools.Gui")]
[assembly: AssemblyCopyright("Copyright © github.com.trondr 2018")]
[assembly: CLSCompliant(false)]
[assembly: AssemblyInformationalVersion("1.0.18022.2.1091f1a")]
[assembly: AssemblyVersion("1.0.18022.2")]
[assembly: AssemblyFileVersion("1.0.18022.2")]


